project:
  type: website

website:
  title: "Introducción a R para Lingüistas"
  navbar:
    background: dark
    left:
      - text: "Antes de empezar"
        href: index.qmd#instalacion
      - text: "Parte I: R básico"
        href: index.qmd#parte-i
      - text: "Parte II: Tidyverse"
        href: index.qmd#parte-ii
      - text: "Parte III: Corpus"
        href: index.qmd#parte-iii
      - text: "Parte IV: tidytext"
        href: index.qmd#parte-iv
      - text: "Parte V: quanteda"
        href: index.qmd#parte-v
      - text: "Parte VI: udpipe"
        href: index.qmd#parte-vi
      - text: "Parte VII: ggplot2"
        href: index.qmd#parte-vii
    right:
      - text: "Universidad de Navarra"
        href: https://www.unav.edu

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 2
    toc-title: "Contenidos"
    smooth-scroll: true
    code-tools: true
    highlight-style: github
