project:
  type: website

website:
  title: "Introducción a R para Lingüistas"
  navbar:
    background: dark
    logo: "https://www.unav.edu/documents/10162/30622995/Marca+Universidad+de+Navarra_200__white.png/75601112-72f9-4940-a060-0a15ab28a11c?t=1635332708035"
    logo-alt: "Universidad de Navarra"
    right:
      - icon: github
        href: https://github.com/AritzUMA/runav
        aria-label: GitHub
      - icon: twitter-x
        href: https://twitter.com/aritz_gorostiza
        aria-label: Twitter

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 2
    toc-title: "Contenidos"
    smooth-scroll: true
    code-tools: true
    highlight-style: github
