project:
  type: website

website:
  title: ""
  navbar:
    background: dark
    right:
      - text: "Universidad de Navarra"
        href: https://www.unav.edu
      - icon: search
        href: search.html

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 2
    toc-title: "Contenidos"
    smooth-scroll: true
    code-tools: true
    highlight-style: github
